<?xml version='1.0' encoding='UTF-8'?><definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:tns="http://isirws.cca.cz/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://isirws.cca.cz/types/" xmlns="http://schemas.xmlsoap.org/wsdl/" name="IsirWsCuzkService" targetNamespace="http://isirws.cca.cz/">
  <types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:tns="http://isirws.cca.cz/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://isirws.cca.cz/types/" xmlns="http://schemas.xmlsoap.org/wsdl/">
      
  <xsd:import namespace="http://isirws.cca.cz/types/" schemaLocation="https://isir.justice.cz:8443/isir_cuzk_ws/IsirWsCuzkService?xsd=isirWsCuzkTypes.xsd"/>
    
</xsd:schema>
  </types>
  <message name="getIsirWsCuzkData">
    <part element="ns1:getIsirWsCuzkDataRequest" name="parameters">
    </part>
  </message>
  <message name="getIsirWsCuzkDataResponse">
    <part element="ns1:getIsirWsCuzkDataResponse" name="parameters">
    </part>
  </message>
  <portType name="IsirWsCuzkPortType">
    <operation name="getIsirWsCuzkData">
      <input message="tns:getIsirWsCuzkData">
    </input>
      <output message="tns:getIsirWsCuzkDataResponse">
    </output>
    </operation>
  </portType>
  <binding name="IsirWsCuzkPortTypeBinding" type="tns:IsirWsCuzkPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="getIsirWsCuzkData">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="IsirWsCuzkService">
    <port binding="tns:IsirWsCuzkPortTypeBinding" name="IsirWsCuzkPortType">
      <soap:address location="https://isir.justice.cz:8443/isir_cuzk_ws/IsirWsCuzkService"/>
    </port>
  </service>
</definitions>
